application: your-project-id
module: default
version: dev
runtime: php55
api_version: 1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: 30ms

includes:
  - handlers.yaml

env_variables:
  DB_NAME: 'localhost'
  DB_USER: 'root'
  DB_PASSWORD: ''
  DB_HOST: 'wordpress_db'
  AUTH_KEY: 'put your unique phrase here'
  SECURE_AUTH_KEY: 'put your unique phrase here'
  LOGGED_IN_KEY: 'put your unique phrase here'
  NONCE_KEY: 'put your unique phrase here'
  AUTH_SALT: 'put your unique phrase here'
  SECURE_AUTH_SALT: 'put your unique phrase here'
  LOGGED_IN_SALT: 'put your unique phrase here'
  NONCE_SALT: 'put your unique phrase here'  

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?\.md$
