handlers:
- url: /wp-(.+)/(.*\.(js|css|htm|html|map|ico|jpg|jpeg|png|gif|svg))$
  static_files: web/wp/wp-\1/\2
  upload: web/wp/wp-(.+)/.*\.(js|css|htm|html|map|ico|jpg|jpeg|png|gif|svg)$
  application_readable: true  

- url: /(.*\.(htm|html|css|js|map|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: web/\1
  upload: web/.*\.(htm|html|css|js|map|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /wp-admin/(.+)
  script: web/wp/wp-admin/\1
  secure: always

- url: /wp-admin/
  script: web/wp/wp-admin/index.php
  secure: always

- url: /wp-login.php
  script: web/wp/wp-login.php
  secure: always

- url: /wp-cron.php
  script: web/wp/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: web/wp/xmlrpc.php

- url: /wp-(.+).php
  script: web/wp/wp-\1.php

- url: /(.+)?/?
  script: web/wp/index.php
