handlers:
- url: /wp-content/uploads/(.*\.(js|css|htm|html|map|ico|jpg|jpeg|png|gif|svg))$
  script: web/static.php
  
- url: /(android-icon|apple-icon|ms-icon|favicon).*
  script: web/static.php  
  
- url: /robots.txt
  static_files: web/robots.txt
  upload: web/robots.txt 
    
- url: /wp-(.+)/(.*\.(js|css|htm|html|map|ico|jpg|jpeg|png|gif|svg))$
  static_files: web/wp/wp-\1/\2
  upload: web/wp/wp-(.+)/.*\.(js|css|htm|html|map|ico|jpg|jpeg|png|gif|svg)$
  application_readable: true  

- url: /(.*\.(htm|html|css|js|map|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: web/\1
  upload: web/.*\.(htm|html|css|js|map|ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /wp-admin/(.+)
  script: web/wp/wp-admin/\1

- url: /wp-admin/
  script: web/wp/wp-admin/index.php

- url: /wp-login.php
  script: web/wp/wp-login.php

- url: /wp-cron.php
  script: web/wp/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: web/wp/xmlrpc.php

- url: /wp-(.+).php
  script: web/wp/wp-\1.php

- url: /_ah/start
  script: web/stopstart.php
  
- url: /_ah/stop
  script: web/stopstart.php

- url: /(.+)?/?
  script: web/index.php
